-- Seed data for testing
-- Note: These use placeholder UUIDs and won't work with actual auth

-- Example submissions (for testing queries)
-- These would normally be inserted by the extension

/*
INSERT INTO submissions (
  id, user_id, problem_slug, problem_title, difficulty, tags,
  status, runtime_ms, runtime_percentile, memory_mb, memory_percentile,
  attempt_number, time_elapsed_seconds, language, code, code_length,
  session_id, submitted_at
) VALUES
(
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000001'::UUID,
  'two-sum',
  'Two Sum',
  'Easy',
  ARRAY['array', 'hash-table'],
  'Accepted',
  4,
  95.5,
  14.2,
  80.0,
  1,
  120,
  'python3',
  'class Solution:\n    def twoSum(self, nums, target):\n        seen = {}\n        for i, n in enumerate(nums):\n            if target - n in seen:\n                return [seen[target - n], i]\n            seen[n] = i',
  182,
  gen_random_uuid(),
  NOW() - INTERVAL '1 hour'
),
(
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000001'::UUID,
  'add-two-numbers',
  'Add Two Numbers',
  'Medium',
  ARRAY['linked-list', 'math', 'recursion'],
  'Wrong Answer',
  NULL,
  NULL,
  NULL,
  NULL,
  1,
  300,
  'python3',
  'class Solution:\n    def addTwoNumbers(self, l1, l2):\n        # Wrong implementation\n        return None',
  89,
  gen_random_uuid(),
  NOW() - INTERVAL '30 minutes'
);
*/

-- The actual seed data will be generated by using the extension
-- This file serves as documentation for the expected data format
