steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg NEXT_PUBLIC_SUPABASE_URL=$$SUPABASE_URL \
          --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=$$SUPABASE_ANON_KEY \
          --build-arg NEXT_PUBLIC_API_URL=$$API_URL \
          -t gcr.io/$PROJECT_ID/leetloop-web:latest \
          -f clients/web/Dockerfile \
          .
    secretEnv: ['SUPABASE_URL', 'SUPABASE_ANON_KEY', 'API_URL']

images:
  - 'gcr.io/$PROJECT_ID/leetloop-web:latest'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/supabase-url/versions/latest
      env: 'SUPABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/supabase-anon-key/versions/latest
      env: 'SUPABASE_ANON_KEY'
    - versionName: projects/$PROJECT_ID/secrets/api-url/versions/latest
      env: 'API_URL'
