"""Pydantic schemas for System Design Review feature."""

from datetime import datetime
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, Field


# ============ Track Models ============


class TopicInfo(BaseModel):
    """A topic within a system design track."""

    name: str
    order: int
    difficulty: str  # "easy", "medium", "hard"
    example_systems: list[str] = []


class RubricWeights(BaseModel):
    """Rubric dimension weights for grading."""

    depth: int = Field(default=3, ge=1, le=5)
    tradeoffs: int = Field(default=3, ge=1, le=5)
    clarity: int = Field(default=2, ge=1, le=5)
    scalability: int = Field(default=2, ge=1, le=5)


class SystemDesignTrack(BaseModel):
    """A system design interview prep track."""

    id: UUID
    name: str
    description: Optional[str] = None
    track_type: str  # "mle", "traditional", "infra", "data"
    topics: list[TopicInfo] = []
    total_topics: int = 0
    rubric: RubricWeights = RubricWeights()
    created_at: Optional[datetime] = None


class TrackSummary(BaseModel):
    """Summary view of a track (for listing)."""

    id: UUID
    name: str
    description: Optional[str] = None
    track_type: str
    total_topics: int


# ============ Question Models ============


class GeneratedQuestion(BaseModel):
    """A question generated by Gemini for a session."""

    id: int  # 0-indexed question number
    text: str
    focus_area: str  # e.g., "data modeling", "scaling", "failure handling"
    key_concepts: list[str] = []  # Concepts the answer should cover


class QuestionResponse(BaseModel):
    """User's response to a question."""

    question_id: int
    response_text: str


# ============ Session Models ============


class CreateSessionRequest(BaseModel):
    """Request to start a new system design session."""

    track_id: UUID
    topic: str
    session_type: str = "track"  # "track", "gap_fill", "review"


class SessionQuestion(BaseModel):
    """A question with optional user response."""

    id: int
    text: str
    focus_area: str
    key_concepts: list[str] = []
    response: Optional[str] = None
    word_count: Optional[int] = None


class SystemDesignSession(BaseModel):
    """A system design review session."""

    id: UUID
    user_id: UUID
    track_id: Optional[UUID] = None
    topic: str
    questions: list[SessionQuestion] = []
    session_type: Optional[str] = None
    status: str = "in_progress"
    started_at: datetime
    completed_at: Optional[datetime] = None


class SubmitResponseRequest(BaseModel):
    """Request to submit a response for a question."""

    question_id: int
    response_text: str


# ============ Grading Models ============


class RubricScore(BaseModel):
    """Score for a single rubric dimension."""

    dimension: str  # "depth", "tradeoffs", "clarity", "scalability"
    score: int = Field(ge=1, le=3)  # 1-3 scale
    feedback: str


class QuestionGrade(BaseModel):
    """Grade for a single question."""

    question_id: int
    score: float = Field(ge=1, le=10)
    feedback: str
    rubric_scores: list[RubricScore] = []
    missed_concepts: list[str] = []


class SessionGrade(BaseModel):
    """Complete grading result for a session."""

    id: UUID
    session_id: UUID
    overall_score: float = Field(ge=1, le=10)
    overall_feedback: str
    question_grades: list[QuestionGrade] = []
    strengths: list[str] = []
    gaps: list[str] = []
    review_topics: list[str] = []
    would_hire: Optional[bool] = None
    graded_at: datetime


class GradingRequest(BaseModel):
    """Request to grade a completed session."""

    # No additional fields needed - session ID in path


# ============ Review Queue Models ============


class SystemDesignReviewItem(BaseModel):
    """A topic in the spaced repetition review queue."""

    id: UUID
    user_id: UUID
    track_id: Optional[UUID] = None
    topic: str
    reason: Optional[str] = None
    priority: int = 0
    next_review: datetime
    interval_days: int = 1
    review_count: int = 0
    last_reviewed: Optional[datetime] = None
    source_session_id: Optional[UUID] = None
    created_at: datetime


class CompleteReviewRequest(BaseModel):
    """Request to mark a review as complete."""

    success: bool


class CompleteReviewResponse(BaseModel):
    """Response after completing a review."""

    id: UUID
    next_review: datetime
    new_interval_days: int


# ============ Progress Models ============


class UserTrackProgress(BaseModel):
    """User's progress on a system design track."""

    id: UUID
    user_id: UUID
    track_id: UUID
    completed_topics: list[str] = []
    sessions_completed: int = 0
    average_score: float = 0.0
    started_at: datetime
    last_activity_at: datetime


class TrackProgressResponse(BaseModel):
    """Track details with user progress."""

    track: SystemDesignTrack
    progress: Optional[UserTrackProgress] = None
    completion_percentage: float = 0.0
    next_topic: Optional[str] = None


# ============ History Models ============


class SessionHistoryItem(BaseModel):
    """Summary of a past session for history view."""

    id: UUID
    track_name: Optional[str] = None
    topic: str
    session_type: Optional[str] = None
    status: str
    overall_score: Optional[float] = None
    started_at: datetime
    completed_at: Optional[datetime] = None


class SessionHistoryResponse(BaseModel):
    """List of past sessions with pagination."""

    sessions: list[SessionHistoryItem]
    total: int
    has_more: bool


# ============ Gemini Context Models ============


class GeminiQuestionContext(BaseModel):
    """Context sent to Gemini for question generation."""

    track_type: str
    topic: str
    example_systems: list[str] = []
    user_weak_areas: list[str] = []
    previous_topics_covered: list[str] = []


class GeminiGradingContext(BaseModel):
    """Context sent to Gemini for grading."""

    track_type: str
    topic: str
    rubric: RubricWeights
    questions: list[dict]  # [{text, focus_area, key_concepts, response}]


class GeminiQuestionResponse(BaseModel):
    """Gemini's generated questions."""

    questions: list[GeneratedQuestion]


class GeminiGradingResponse(BaseModel):
    """Gemini's grading response."""

    overall_score: float = Field(ge=1, le=10)
    overall_feedback: str
    question_grades: list[QuestionGrade]
    strengths: list[str] = []
    gaps: list[str] = []
    review_topics: list[str] = []
    would_hire: Optional[bool] = None


# ============ Dashboard Integration Models ============


class UserSystemDesignSettings(BaseModel):
    """User's system design settings for dashboard integration."""

    id: UUID
    user_id: UUID
    active_track_id: Optional[UUID] = None
    show_on_dashboard: bool = True
    daily_topic_enabled: bool = True
    created_at: datetime
    updated_at: datetime


class SetActiveTrackRequest(BaseModel):
    """Request to set active system design track."""

    track_id: Optional[UUID] = None  # None to clear active track


class NextTopicInfo(BaseModel):
    """Information about the next topic to practice."""

    track_id: UUID
    track_name: str
    track_type: str
    topic_name: str
    topic_order: int
    topic_difficulty: str
    example_systems: list[str] = []
    topics_completed: int
    total_topics: int


class SystemDesignDashboardSummary(BaseModel):
    """Summary for dashboard display."""

    has_active_track: bool
    active_track: Optional[TrackSummary] = None
    next_topic: Optional[NextTopicInfo] = None
    reviews_due_count: int = 0
    reviews_due: list[SystemDesignReviewItem] = []
    recent_score: Optional[float] = None
    sessions_this_week: int = 0
