-- Populate ideal_answer JSONB for the 9 validated LP STAR stories

-- 1. GenAI Fluency — Generative Retrieval Pipeline
UPDATE onsite_prep_questions SET ideal_answer = '{
  "summary": "Designed a GenAI-powered generative retrieval pipeline at Walmart to solve cold-start recommendations across 3 NA markets.",
  "outline": [
    "Situation: 90%+ of catalog items had zero purchase data; traditional collaborative filtering was impossible, especially in emerging markets like Mexico.",
    "Task: Design a GenAI recommendation architecture that works for cold-start items and users across US, CA, and MX.",
    "Action: Built a generative retrieval pipeline where an LLM generates shopping intents and semantic queries from item attributes, feeding into existing search infrastructure (Solr, FAISS). Ran as offline batch signal with daily delta updates across 3M anchors. Also shipped Item Compare for CA/MX. Fixed price-awareness gap in two phases (reranking hotfix + retrieval retrain). Killed query expansion prototype when data showed it was unviable.",
    "Result: Pipeline serves all 3 NA markets with full catalog coverage including zero-history items. Item Compare launched in CA/MX. Query expansion kill saved ongoing cost. Key insight: GenAI solves problems traditional ML fundamentally cannot, like cold start at scale."
  ],
  "full_response": "At Walmart, our international personalization team faced a fundamental cold-start challenge. In mature markets like the US, over 90% of catalog items had never been purchased — the catalog was massively underexplored. In emerging markets like Mexico, the problem was even more extreme: virtually no engagement data existed, meaning nearly 100% of items had zero signal. Traditional collaborative filtering was a non-starter — you can''t recommend based on co-purchase patterns when purchase data doesn''t exist. Leadership had identified GenAI as a strategic priority, but there was no concrete architecture for how to apply it to recommendation at scale.\n\nI needed to design a GenAI-powered recommendation architecture that could generate personalized recommendations for any item or user — including cold-start scenarios — across all three North American markets.\n\nI designed a generative retrieval pipeline: for each anchor (user or item), an LLM generates shopping intents and semantic queries, which then feed into our existing search infrastructure (Solr, FAISS) to retrieve a ranked list of recommendations. This was a fundamentally different approach from collaborative filtering — instead of learning from past purchase patterns, we were generating the reasoning about what a user might want next. The system runs as an offline batch signal with daily delta updates across 3M anchor items, prioritizing the most popular items for freshness.\n\nI also shipped a second GenAI feature, Item Compare, where an LLM generates use cases and highlights for ~300K items in high-traffic categories across CA and MX, letting customers compare products side-by-side.\n\nAfter launch, our PM flagged that results weren''t price-aware — a critical gap for our cost-conscious customers. I executed a two-phase fix: a reranking hotfix in 2 weeks to inject price sensitivity, then a 6-week effort to retrain the retrieval model on price-aware queries for a permanent solution.\n\nSeparately, I evaluated GenAI for search bar query expansion. We prototyped it, but the combination of latency, cost, and degrading relevance lift made it unviable. We killed it based on the data.\n\nThe generative retrieval pipeline serves all three NA markets, providing personalized recommendations with full catalog coverage — including items with zero purchase history. Item Compare launched in CA/MX. The query expansion kill saved ongoing cost with no relevance loss. The key insight: GenAI''s biggest value in recommendation isn''t replacing traditional ML — it''s solving problems traditional ML fundamentally can''t, like cold start at scale."
}'::jsonb WHERE id = '597fa4ea-ab77-4958-9f7c-db37bcc3cea5';

-- 2. Insist on Highest Standards — Intent-Based Index Cannibalization Pushback
UPDATE onsite_prep_questions SET ideal_answer = '{
  "summary": "Blocked launch of an undifferentiated recommendation index at Walmart by quantifying cannibalization and building an orthogonality metric.",
  "outline": [
    "Situation: PMs wanted to copy-paste a US intent-based recommendation index to international markets without validation. LLM-as-judge evaluation showed it was cannibalizing the existing complementary items carousel.",
    "Task: Block the launch and demonstrate why shipping an undifferentiated index would hurt the page experience.",
    "Action: Used LLM-as-judge framework to quantify overlap. Developed a vector entropy orthogonality metric measuring differentiation in embedding space. Guided retraining with explicit differentiation objectives.",
    "Result: Differentiated index shipped 2-4 weeks later with 10-15 bps GMV lift. Orthogonality metric became reusable tool for evaluating any new index against existing ones."
  ],
  "full_response": "At Walmart, PMs wanted to launch an intent-based recommendation index in international markets by replicating what existed in the US. The approach was essentially copy-paste — port the US model to CA/MX and ship it. The problem was twofold: they had no offline metric to validate whether the index actually worked correctly in these markets, and when I evaluated it using the LLM-as-judge framework I''d built, I found the intent-based index was generating recommendations nearly identical to the existing complementary items carousel. Two carousels on the same page were cannibalizing each other rather than providing distinct value to customers.\n\nI needed to block the launch and show the team why shipping an undifferentiated index would hurt the overall page experience — even if the individual carousel looked fine in isolation.\n\nFirst, I used the LLM-as-judge evaluation framework to demonstrate the cannibalization quantitatively — the intent-based results overlapped heavily with complementary items, meaning customers would see near-identical recommendations in multiple carousels. The PMs didn''t have any offline success metric; they were relying on the US version having worked as justification. I showed that \"it worked in the US\" wasn''t evidence it would work here — especially when the page composition was different and the index was duplicating an existing signal.\n\nBut diagnosing the problem wasn''t enough — I needed to provide the path forward. I developed a vector entropy orthogonality metric that measured how differentiated two recommendation indices were in embedding space. This gave the team a concrete, measurable target: we could see exactly how much the indices overlapped and set a threshold for acceptable differentiation. The metric guided the fix — we retrained the intent-based index with objectives that explicitly pushed it toward distinct recommendation territory, ensuring each carousel served a different purpose on the page.\n\nThe differentiated intent-based index shipped about 2-4 weeks later with 10-15 bps GMV lift. Without the pushback, we would have launched an index that cannibalized existing recommendations — wasting weeks of A/B experimentation time and potentially degrading the overall page experience. The orthogonality metric became a reusable tool for evaluating any new index against existing ones before committing to A/B."
}'::jsonb WHERE id = '3c265257-4a5f-47d5-9595-39b47cee1ea5';

-- 3. Bias for Action — Post-A/B Metrics Dashboard
UPDATE onsite_prep_questions SET ideal_answer = '{
  "summary": "Built a full metrics dashboard from scratch at Walmart to properly evaluate model launches instead of waiting on another team''s roadmap.",
  "outline": [
    "Situation: Post-A/B analysis relied on tabular Adobe dashboards managed by analytics team — no graphs, no journey breakdowns, no head-to-head A/B comparison.",
    "Task: Needed granular evaluation of model launches to see where gains and regressions were hiding.",
    "Action: Built a complete metrics dashboard tracking revenue per customer, CTR by journey step and module, with A/B experiment key filtering. Built it for myself first, then shared with team.",
    "Result: Dashboard became team''s primary launch evaluation tool. Gave granular visibility into which journey steps drove lift. Turned months of cross-team coordination into a weekend project."
  ],
  "full_response": "At Walmart, the team''s post-A/B analysis relied on Adobe dashboards managed by the analytics team. The dashboards were tabular only — no graphs, no way to cleanly view GMV lift over time, no ability to break down results by step in the user journey or by module. There was no clean way to do head-to-head A/B comparison. We were making launch decisions based on incomplete data views. The analytics team had their own roadmap and priorities across multiple orgs — our ML-specific visualization needs weren''t their top priority, and reasonably so.\n\nI needed a way to properly evaluate whether our model launches were working — not just top-line metrics, but granular breakdowns that would tell me where gains were coming from and where regressions were hiding.\n\nRather than waiting on another team''s roadmap, I built a full metrics dashboard from scratch. It tracked revenue per customer, click-through rate broken down by step in the user journey and by module, with filtering by A/B experiment key for head-to-head comparison. I built it for myself first, then shared it with the team. This was squarely the analytics team''s domain, not mine — my job was ML science — but I had a specific need and the skills to address it quickly.\n\nThe dashboard became the team''s primary tool for evaluating launches. It gave us granular visibility — we could see exactly which user journey steps were driving lift and which were flat. This directly informed model iteration decisions and helped us diagnose issues that the tabular Adobe reports would have missed. Building it myself turned what would have been months of cross-team coordination into a weekend project."
}'::jsonb WHERE id = '50ca11e3-b667-4367-a8ac-48f1c1e1e40e';

-- 4. Ownership — DS/MLOps Operating Model
UPDATE onsite_prep_questions SET ideal_answer = '{
  "summary": "Redesigned the DS/MLOps handoff workflow at Walmart to eliminate translation failures by having scientists own pipeline code end-to-end.",
  "outline": [
    "Situation: Structural split between DS (model builders) and MLOps (production deployers) caused bugs during code translation and buried MLOps in rewrite work.",
    "Task: Change how DS and MLOps collaborated so models could ship reliably without drowning MLOps in translation work.",
    "Action: Demonstrated end-to-end ownership on own projects first. Proposed process change: DS owns pipeline code from day one. Introduced joint design reviews, shared design docs, and validation contracts. Framed it as freeing MLOps for higher-value work.",
    "Result: Projects using the unified design review had zero handoff failures. Pattern became team default. MLOps capacity freed up for KTLO and refactoring."
  ],
  "full_response": "On Walmart''s International Personalization team, there was a structural split between data scientists who built models and MLOps engineers who brought them to production. On the US search team I''d come from, there was no such distinction — scientists owned everything end-to-end, which meant no gaps in ownership. On the international team, the workflow was: DS builds a prototype in isolation, hands off a finished artifact, and MLOps reverse-engineers production pipeline code from it. This created two systematic failure modes. First, MLOps would introduce bugs during the translation — they lacked context on design decisions, so subtle things broke. Second, MLOps couldn''t focus on their actual core job — uptime, KTLO, refactoring existing signals — because they were buried in rewrite work for new launches.\n\nI needed to change how DS and MLOps collaborated so that new models could ship reliably without drowning the MLOps team in translation work. This wasn''t about one pipeline — the same failure mode was repeating across the similar items index, the embedding pipelines, and other signals.\n\nI started by demonstrating the end-to-end model on my own projects — writing production pipeline code myself in Airflow with Spark and PyTorch Lightning, carrying it through to production as a single code owner. Once I had concrete evidence that the pattern worked, I proposed a process change to the team: DS owns the pipeline code from day one, not prototype code that gets rewritten. I introduced three elements. First, a joint design review early — DS and MLOps align on pipeline architecture, GPU provisioning, and data volumes before anyone writes code. Second, a single design doc that both sides contribute to — a shared source of truth so context isn''t lost in handoff. Third, a validation contract upfront — agreed-upon success criteria like inference throughput targets, data freshness expectations, and monitoring plans.\n\nThere was natural tension because redefining the handoff boundary felt like scope erosion to the MLOps side. I framed it differently: this wasn''t taking scope from MLOps, it was removing translation work that was drowning them so they could focus on higher-value work.\n\nThe projects that went through the unified design review process had zero handoff failures. The pattern — scientist owns the pipeline, MLOps owns reliability — became the team''s default for new launches. It worked because it respected what each side was actually good at: scientists had the model context to write correct pipeline code, MLOps had the production expertise to ensure uptime and infrastructure quality. MLOps capacity freed up from rewrite work went back into KTLO and refactoring existing signals."
}'::jsonb WHERE id = '5b75e08e-664d-40c9-8016-9c02b611e7a1';

-- 5. Earn Trust — Embedding Pipeline Bug
UPDATE onsite_prep_questions SET ideal_answer = '{
  "summary": "Owned a stale embedding bug publicly at Walmart, ran a blameless post-mortem, and fundamentally changed how I approach post-launch monitoring.",
  "outline": [
    "Situation: Built an embedding pipeline with an MD5 hash bug — items with changed attributes wouldn''t get re-embedded. Bug made it through code review to production.",
    "Task: A colleague found the stale embedding bug 3 weeks later during an unrelated investigation. Less than 1% of items affected, but at scale it mattered.",
    "Action: Owned the mistake immediately. Ran blameless post-mortem, drafted org-wide shareout emails. Didn''t blame code reviewers. Identified root cause as fire-and-forget approach to shipped features.",
    "Result: Team didn''t hold it against me. Experience fundamentally changed my approach — built monitoring into every pipeline and established habit of continuous post-release observation. Gained deep trust for the colleague who found it."
  ],
  "full_response": "Earlier in my time at Walmart, I built an embedding pipeline for our search retrieval system. The pipeline computed MD5 hashes to determine which items needed re-embedding. I had a bug: when a catalog attribute key changed — for example, a product title was updated — items already in the index wouldn''t get new embeddings because the hash logic didn''t account for the attribute change. The bug went through code review and made it to production.\n\nThree weeks later, a colleague was doing a root cause analysis on a separate evaluation issue. While diving deep into my pipeline, they discovered the stale embedding bug. It wasn''t causing the degradation they were investigating, but they flagged it. Less than 1% of items were affected, but at scale with dense retrieval, incorrect embeddings matter — search results were degraded for those items.\n\nI owned the mistake immediately. I ran a blameless post-mortem within the team and drafted shareout emails to the wider org explaining what happened, the impact, and the fix. I didn''t downplay it or blame the code reviewers who had also missed it. The deeper issue was that I had a fire-and-forget approach to shipped features — I built it, deployed it, and moved on without monitoring for exactly this class of silent degradation.\n\nThe team didn''t hold it against me — mistakes happen, especially with a junior engineer learning production systems. But the experience fundamentally changed how I work. I learned that ownership doesn''t end at launch. After this, I built monitoring into every pipeline I shipped and established the habit of continuous observation post-release. I also gained deep trust for the colleague who found the bug — they earned my respect by diving deep into someone else''s code without hesitation."
}'::jsonb WHERE id = '6ed53c11-47ab-4edf-8e25-cd7a51186f41';

-- 6. Have Backbone; Disagree & Commit — LLM vs Pure Embedding Debate
UPDATE onsite_prep_questions SET ideal_answer = '{
  "summary": "Defended an LLM-based generative retrieval architecture against team skepticism by preemptively building both approaches and presenting comparative results.",
  "outline": [
    "Situation: Designed an architecture using LLM-generated natural language as intermediary for retrieval. Peers thought this was bizarre vs staying in embedding space.",
    "Task: Defend why the LLM-based architecture was superior for complementary recommendations despite looking unconventional.",
    "Action: Built both architectures before the debate. Presented comparative results showing LLM-based won on diversity and relevance (world knowledge enables true complements), interpretability (readable queries vs opaque probes), and modularity (reusable components). Speed objection didn''t apply for offline batch.",
    "Result: Data made the case. Shipped LLM-based architecture. Generated label data became shared asset across multiple team projects."
  ],
  "full_response": "For our generative retrieval pipeline at Walmart, I designed an architecture that uses natural language as an intermediary: item attributes go into an LLM which generates text queries, those queries feed into a text encoder for dense retrieval, and the results are evaluated by an LLM judge. Peers on the team thought this was bizarre — why generate natural language text as a middle step when you could stay entirely in embedding space?\n\nI anticipated this opposition. The alternative architecture was a pure embedding approach: item embeddings feed into a ComiRec retrieval model trained on LLM-generated relevance labels, with multiple embedding probes for diversity, followed by dense retrieval and reranking. It was faster, cheaper, and avoided the bizarre text generation step. I needed to defend why the LLM-based architecture was superior for our use case.\n\nBefore the debate even happened, I built both architectures and trained them. When peers raised concerns during our weekly experimental shareout, I presented comparative results. Architecture 1 (LLM-based) outperformed on both diversity and relevance because it leveraged the LLM''s world knowledge directly — a one-shot dense retrieval model only gets a clustering of similar items, but for complementary signal you need genuine diversity (gaming chair and gaming mouse are both good complements for gaming keyboard). I also showed that interpretability was better — the generated queries are human-readable versus opaque embedding probes. And the speed objection didn''t apply because this was an offline batch signal, not real-time serving. Finally, the LLM-based pipeline produced modular components — the query generation and retrieval models could be reused separately on other projects. The label data I generated was used by other teams for hard negatives in similar items retrieval.\n\nPeople were surprised I''d preempted the objection by building both. The data made the case. We shipped the LLM-based architecture, and I continued pushing this development loop despite ongoing pressure to just do SFT. The generated label data became a shared asset across multiple team projects."
}'::jsonb WHERE id = 'afd21ab0-8e59-4e83-ab14-de777eefa94e';

-- 7. Learn & Be Curious — Papers to Production
UPDATE onsite_prep_questions SET ideal_answer = '{
  "summary": "Systematically implemented cutting-edge research papers (DeepRetrieval, ComiRec, SASRec, Choppy) into production at Walmart, comparing 10+ architectures.",
  "outline": [
    "Situation: Personalization team had been heads-down shipping for 2 years. Gap between published research and deployed methods. No bandwidth to close that loop.",
    "Task: Push the technical frontier by implementing promising research methods and empirically comparing them against existing approaches.",
    "Action: Implemented DeepRetrieval (RL-based query generation with LoRA fine-tuning, PPO/GRPO), ComiRec (DR and SA variants), SASRec, Choppy. Built substantial infrastructure: optimized vLLM 1→10 inferences/sec, custom SQLite caching for billions of pairwise predictions. Compared 10+ architectures with full hyperparameter sweeps.",
    "Result: ComiRec-SA won for user-item retrieval. RL-trained model powers generative retrieval across 3 NA markets. Cached predictions became shared data asset for SFT. Each paper expanded team''s technical toolkit."
  ],
  "full_response": "At Walmart, the personalization and search teams were building recommendation and retrieval systems that needed to perform at scale across three markets. The team had been heads-down shipping product for two years straight — they''d built a working system across three markets, which was a real achievement. But there was a gap between what the research community was publishing and what we were deploying. Existing approaches hadn''t been rigorously compared against newer methods, and there hadn''t been bandwidth to close that loop while simultaneously keeping the lights on across US, CA, and MX.\n\nI wanted to push the technical frontier of what we could build by going directly to the research literature, implementing promising methods, and empirically comparing them against our existing approaches.\n\nI systematically read papers and implemented them from scratch for production use. I implemented DeepRetrieval''s approach to RL-based query generation — LoRA fine-tuning Llama 3.2 with PPO and GRPO using explicit reward functions. This required building substantial infrastructure: I optimized vLLM for inference at scale, taking throughput from about 1 inference per second to 10 through KV cache tuning, batch size optimization, and tensor parallelism across 8 GPUs. I built a custom SQLite caching layer for the RL reward loop that scaled to billions of pairwise predictions — this cache data was then reusable for SFT on other models. I implemented ComiRec (both DR and SA variants) for sequential recommendation with diversity, SASRec, and Choppy for ranked list truncation. In total I compared 10+ architectures with full hyperparameter sweeps.\n\nComiRec-SA won the architecture comparison for user-item retrieval — strong retrieval for engaged items with good diversity. The RL-trained query generation model powers the generative retrieval pipeline serving all three NA markets. The billions of cached pairwise predictions became a shared data asset for SFT across multiple team projects. Each paper I implemented expanded the team''s technical toolkit and raised the bar for what we considered good enough."
}'::jsonb WHERE id = '12ade793-d5c9-4de3-a940-5794d3dd73dc';

-- 8. Dive Deep — Similar Items Pipeline
UPDATE onsite_prep_questions SET ideal_answer = '{
  "summary": "Investigated and rewrote Walmart''s similar items pipeline from proof of concept to reliable production across 3 markets with ~100x throughput improvement.",
  "outline": [
    "Situation: Similar items pipeline was a POC that launched in Mexico but failed scaling to other markets. Over-provisioned A100s, CPU inference instead of GPU, unevaluated image embeddings. DS-to-MLOps handoff lost context.",
    "Task: Understand what was actually wrong, fix it, and get the pipeline running reliably in all 3 markets.",
    "Action: Wrote an LLM-judge evaluation rubric for similar items (none existed). Used it to test assumptions — removed image embeddings when rubric showed no quality impact. Rewrote in PyTorch Lightning with multi-GPU V100 support. Owned full pipeline as single code owner.",
    "Result: Pipeline went from partially working in 1 market to reliable across US, CA, MX with ~100x throughput improvement. Evaluation rubric gave team systematic way to make evidence-based design decisions."
  ],
  "full_response": "When I joined Walmart''s International Personalization team, I started by reviewing what pipelines were actually running in production. The similar items pipeline had been built as a proof of concept and successfully launched in Mexico — that was the foundation that showed the approach worked. But as the team tried to scale it to all three markets, the architecture hit limits. It was provisioned on A100s for a text encoder that didn''t need that much compute, was doing inference on Spark CPU workers instead of GPU, and had image embeddings added for secondary filtering that had never been evaluated for impact. The pipeline ran partially in Mexico but was failing in the other markets. There was also a structural challenge: data scientists built models and MLOps deployed them, and context was lost in that handoff — neither side felt fully accountable for end-to-end reliability.\n\nThe team recognized the issues but was stretched across multiple workstreams. I believed a production pipeline shouldn''t have persistent failures, and I had the cross-stack skills to investigate. I needed to understand what was actually wrong, fix it, and get it running in all three markets.\n\nI dug into every layer. First, I wrote an LLM-judge evaluation rubric specifically for similar items so I could actually measure quality — no such metric existed before. Then I used that rubric to systematically test assumptions: I removed the image embedding filtering and replaced it with a lighter-weight filter, and the rubric showed quality was equivalent — the image embeddings had been adding complexity with no measurable benefit. I rewrote the embedding generation code in PyTorch Lightning with native multi-GPU support, separating data processing from GPU inference tasks and running on V100s in parallel instead of the A100s they couldn''t reliably provision. I carried the pipeline from rewrite through to production as a single code owner — closing the DS-to-MLOps handoff gap by owning both sides.\n\nThe rewritten pipeline went from partially working in one market to running reliably across all three (US, CA, MX) with roughly 100x throughput improvement. The evaluation rubric gave the team a systematic way to navigate the design space — making evidence-based decisions about what to include or remove rather than relying on intuition about which components were contributing."
}'::jsonb WHERE id = 'e392cf52-019d-4e78-8ead-15d3479b0de6';

-- 9. Deliver Results — EBR Iteration + CIKM 2024
UPDATE onsite_prep_questions SET ideal_answer = '{
  "summary": "Led iterative improvements to Walmart''s core search EBR model across multiple launch cycles, each delivering ~10 bps GMV lift (~$100M annual impact). Published at CIKM 2024.",
  "outline": [
    "Situation: US search EBR system was the primary model powering product search. Had significant gaps: training data noise, poor misspelling handling, no systematic iteration approach.",
    "Task: Deliver sustained, measurable improvements to the core search retrieval model powering all US product search.",
    "Action: Led iterative EBR improvements: relevance reward model from human feedback, hard negative mining, in-batch negatives, dual loss optimization, price-aware retrieval, typo-aware training, semi-positive generation. Each went through offline eval, A/B testing, phased rollout. Published methodology as first author at CIKM 2024.",
    "Result: Each iteration delivered ~10 bps GMV lift (~$100M annual impact at Walmart''s scale). Cumulative improvements made EBR the foundation of Walmart''s search relevance stack."
  ],
  "full_response": "At Walmart, the US search embedding-based retrieval (EBR) system was the primary model powering product search. While the initial EBR deployment had improved relevance over traditional methods, there were significant gaps: training data noise causing relevance degradation, poor handling of misspelled queries, and no systematic approach to iterating on the model.\n\nI needed to deliver sustained, measurable improvements to the core search retrieval model — the system that powers all US product search.\n\nI led a series of iterative improvements to the EBR model over multiple launch cycles. Each iteration targeted a specific weakness: a relevance reward model trained on human feedback to filter noisy training data, hard negative mining to improve fine-grained discrimination, in-batch negatives for training efficiency, dual loss optimization, price-aware retrieval, typo-aware training for query robustness, and semi-positive generation for edge cases. Each launch went through offline evaluation, A/B testing, and phased rollout. I published the methodology as first author at CIKM 2024, documenting the relevance reward model and multi-objective learning approach.\n\nAcross these launches, each iteration delivered approximately 10 bps GMV lift in A/B testing — at Walmart''s search scale, each launch represents roughly $100M in annual impact. The cumulative improvements made EBR the foundation of Walmart''s search relevance stack."
}'::jsonb WHERE id = '6a786a2c-5cf5-4f62-82be-2140ef9ba33e';
