-- Swap Ownership and Have Backbone stories:
-- - Ownership: now Embedding Infrastructure (was DS/MLOps Operating Model)
-- - Have Backbone: now DS/MLOps Operating Model reframed for consensus (was LLM vs Embedding)

-- Also update context_hint on the question rows
UPDATE onsite_prep_questions SET context_hint = 'Embedding Infrastructure — assigned to ML features but international team had no shared embedding platform. Built end-to-end infra (text + user embeddings, compute, store, serve, monitor) that became team-wide standard for all rec pipelines.'
WHERE subcategory = 'Ownership';

UPDATE onsite_prep_questions SET context_hint = 'DS/MLOps Operating Model — disagreed with handoff workflow, MLOps pushed back on scope erosion, reached consensus through joint design reviews and reframed ownership boundaries.'
WHERE subcategory = 'Have Backbone; Disagree & Commit';

-- 1. Ownership — Embedding Infrastructure
UPDATE onsite_prep_questions SET ideal_answer = '{
  "summary": "Built shared embedding infrastructure for Walmart''s international personalization team despite being assigned to ML feature work, creating the platform that all rec pipelines consumed from.",
  "outline": [
    "Situation: International personalization team had no shared embedding infrastructure. Teams ran duplicated ad hoc Spark jobs for text and user embeddings. Features were blocked or delayed by the lack of a reliable, shared embedding source.",
    "Task: Assigned to build ML features (similar items, complementary recs, user recs) — infrastructure was supposed to be someone else''s problem. Realized nothing would ship reliably without a proper embedding platform.",
    "Action: Built end-to-end embedding infrastructure: text and user embedding computation via PyTorch Lightning on multi-GPU, storage and serving layer, monitoring and freshness tracking. Standardized what had been scattered ad hoc Spark jobs into a single pipeline across all three NA markets. Owned compute, storage, and serving as a single code owner.",
    "Result: Became the team-wide standard. All rec pipelines — similar items, complementary recommendations, user-based recs, and search — consumed from it. Eliminated duplicated embedding work and unblocked feature development across the team."
  ],
  "full_response": "When I joined Walmart''s International Personalization team, I was assigned to build ML features — similar items, complementary recommendations, user-based recs. My job was the science and the models, not infrastructure. But when I started scoping my first features, I discovered the international team had no shared embedding infrastructure at all. Teams were running ad hoc Spark jobs to generate embeddings independently — one person''s similar items job would compute text embeddings from scratch, another person''s complementary recs prototype would do the same thing separately. There was no shared storage, no serving layer, no monitoring. Features were blocked or delayed because there was no reliable embedding source to build on, and duplicated work meant wasted GPU hours and inconsistent results across pipelines.\n\nNobody owned this gap. It wasn''t in my scope, and it wasn''t formally in anyone else''s either. The MLOps team was focused on keeping existing production systems running, and the other data scientists were heads-down on their own feature work. But I realized that none of my assigned features would ship reliably without a proper foundation — I''d either spend weeks on one-off embedding generation for every feature, or I could invest upfront in shared infrastructure that everything could build on.\n\nI built the embedding platform end-to-end. For compute, I wrote PyTorch Lightning pipelines for text and user embeddings with native multi-GPU support, replacing the scattered ad hoc Spark jobs with a single, optimized pipeline. I built storage and serving layers so downstream consumers could pull pre-computed embeddings without running their own generation. I added monitoring and freshness tracking so we''d know if embeddings went stale — a lesson from an earlier bug where stale embeddings degraded results silently. I standardized the pipeline across all three NA markets (US, CA, MX), handling catalog differences and scale variations. I owned the full stack as a single code owner — compute, storage, and serving.\n\nThe infrastructure became the team-wide standard. Every rec pipeline — similar items, complementary recommendations, user-based recs, and search retrieval — consumed from it. New features that would have taken weeks to stand up their own embedding generation could launch in days by plugging into the shared platform. The duplicated ad hoc Spark jobs disappeared, freeing up GPU capacity and ensuring consistency across pipelines. What started as a side detour from my assigned feature work became the foundation that everything else was built on."
}'::jsonb WHERE subcategory = 'Ownership';

-- 2. Have Backbone; Disagree & Commit — DS/MLOps Operating Model (consensus framing)
UPDATE onsite_prep_questions SET ideal_answer = '{
  "summary": "Disagreed with the team''s DS-to-MLOps handoff model at Walmart. MLOps pushed back on the proposed change as scope erosion. Reached consensus by demonstrating the pattern first, then reframing ownership so both sides gained.",
  "outline": [
    "Situation: Structural split between DS (model builders) and MLOps (production deployers) caused translation bugs and buried MLOps in rewrite work. Coming from US search where scientists owned everything end-to-end, believed the handoff model was fundamentally broken.",
    "Task: Proposed changing the ownership boundary — DS should own pipeline code from day one. MLOps pushed back hard, viewing this as scope erosion that devalued their role.",
    "Action: Didn''t force the issue. Demonstrated end-to-end ownership on own projects first to build evidence. Then proposed a model addressing both sides'' concerns: DS owns code (eliminating translation bugs), MLOps owns reliability (their actual expertise). Introduced joint design reviews, shared design docs, and validation contracts as the coordination mechanism. Framed it as freeing MLOps for higher-value work, not taking their scope.",
    "Result: Both sides gained something. Projects using the new model had zero handoff failures. Pattern became team default. MLOps capacity freed up from rewrite work went back into KTLO and platform improvements. Consensus held because it respected what each side was actually good at."
  ],
  "full_response": "On Walmart''s International Personalization team, there was a structural split between data scientists who built models and MLOps engineers who brought them to production. The workflow was: DS builds a prototype in isolation, hands off a finished artifact, and MLOps reverse-engineers production pipeline code from it. I''d come from the US search team where there was no such distinction — scientists owned everything end-to-end. I believed the handoff model was fundamentally broken. It created two systematic failures: MLOps introduced bugs during translation because they lacked context on design decisions, and they couldn''t focus on their actual core job — uptime, KTLO, refactoring — because they were buried in rewrite work.\n\nI proposed changing the ownership boundary: DS should own the pipeline code from day one, not prototype code that gets rewritten. MLOps pushed back hard. To them, this felt like scope erosion — they''d built their role around owning production code, and now a data scientist was saying they should stop doing that. The concern was legitimate. If DS writes production code, what''s left of the MLOps role? Are they being made redundant?\n\nI didn''t force the issue or escalate. Instead, I started by demonstrating the pattern on my own projects — writing production pipeline code myself in Airflow with Spark and PyTorch Lightning, carrying it through to production as a single code owner. Once I had concrete evidence that the pattern worked and didn''t create chaos, I proposed a model that addressed both sides'' concerns. The key was reframing: this wasn''t DS taking MLOps'' scope, it was removing the translation work that was drowning them so they could focus on what they were actually best at. I introduced three coordination mechanisms both sides helped shape. First, joint design reviews early — DS and MLOps align on pipeline architecture, GPU provisioning, and data volumes before anyone writes code. Second, a shared design doc that both sides contribute to — so context isn''t lost. Third, validation contracts upfront — agreed-upon success criteria like inference throughput targets and monitoring plans. These weren''t my unilateral demands; they emerged from conversations about what MLOps actually needed to trust DS-written code.\n\nBoth sides gained something from the final model. DS got faster shipping without translation bugs. MLOps got freed from rewrite work and could focus on reliability, KTLO, and platform improvements — work they found more meaningful. Projects using the unified design review process had zero handoff failures. The pattern became the team''s default for new launches. The consensus held because it genuinely respected what each side was good at: scientists had the model context to write correct pipeline code, MLOps had the production expertise to ensure uptime and infrastructure quality."
}'::jsonb WHERE subcategory = 'Have Backbone; Disagree & Commit';
