-- ML Coding Drills
-- Static problem bank, daily exercise batches, and spaced repetition review queue
-- for Amazon ML coding interview prep

-- ============ Problems Table (static bank of 10) ============

CREATE TABLE IF NOT EXISTS ml_coding_problems (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  difficulty TEXT NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')),
  category TEXT NOT NULL,
  key_concepts TEXT[] DEFAULT '{}',
  math_concepts TEXT[] DEFAULT '{}',
  estimated_minutes INTEGER NOT NULL DEFAULT 30,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============ Daily Exercises Table ============

CREATE TABLE IF NOT EXISTS ml_coding_daily_exercises (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  problem_id UUID REFERENCES ml_coding_problems(id),
  generated_date DATE NOT NULL DEFAULT CURRENT_DATE,
  sort_order INTEGER NOT NULL DEFAULT 0,

  -- Exercise content (generated by Gemini as a specific variation)
  prompt_text TEXT NOT NULL,
  starter_code TEXT,

  -- User response & grading
  submitted_code TEXT,
  score NUMERIC(4,2) CHECK (score IS NULL OR (score >= 0 AND score <= 10)),
  verdict TEXT CHECK (verdict IS NULL OR verdict IN ('pass', 'fail', 'borderline')),
  feedback TEXT,
  correctness_score NUMERIC(4,2) CHECK (correctness_score IS NULL OR (correctness_score >= 0 AND correctness_score <= 10)),
  code_quality_score NUMERIC(4,2) CHECK (code_quality_score IS NULL OR (code_quality_score >= 0 AND code_quality_score <= 10)),
  math_understanding_score NUMERIC(4,2) CHECK (math_understanding_score IS NULL OR (math_understanding_score >= 0 AND math_understanding_score <= 10)),
  missed_concepts TEXT[] DEFAULT '{}',
  suggested_improvements TEXT[] DEFAULT '{}',

  -- Status
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'skipped')),
  is_review BOOLEAN DEFAULT FALSE,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,

  -- Unique constraint: one exercise per sort position per user per day
  UNIQUE(user_id, generated_date, sort_order)
);

-- ============ Review Queue Table ============

CREATE TABLE IF NOT EXISTS ml_coding_review_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  problem_slug TEXT NOT NULL,
  reason TEXT,
  priority INTEGER DEFAULT 0,
  next_review TIMESTAMPTZ DEFAULT NOW(),
  interval_days INTEGER DEFAULT 1,
  review_count INTEGER DEFAULT 0,
  last_reviewed TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(user_id, problem_slug)
);

-- ============ Indexes ============

CREATE INDEX IF NOT EXISTS idx_ml_coding_daily_exercises_user_date
  ON ml_coding_daily_exercises(user_id, generated_date);

CREATE INDEX IF NOT EXISTS idx_ml_coding_daily_exercises_user_status_date
  ON ml_coding_daily_exercises(user_id, status, generated_date);

CREATE INDEX IF NOT EXISTS idx_ml_coding_review_queue_user_next
  ON ml_coding_review_queue(user_id, next_review);

-- ============ Enable RLS ============

ALTER TABLE ml_coding_problems ENABLE ROW LEVEL SECURITY;
ALTER TABLE ml_coding_daily_exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE ml_coding_review_queue ENABLE ROW LEVEL SECURITY;

-- ============ RLS Policies (Authenticated Users) ============

-- Problems: read-only for all authenticated users
CREATE POLICY "Users can view ml coding problems"
  ON ml_coding_problems FOR SELECT
  USING (true);

-- Daily Exercises
CREATE POLICY "Users can view own ml coding exercises"
  ON ml_coding_daily_exercises FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own ml coding exercises"
  ON ml_coding_daily_exercises FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own ml coding exercises"
  ON ml_coding_daily_exercises FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own ml coding exercises"
  ON ml_coding_daily_exercises FOR DELETE
  USING (auth.uid() = user_id);

-- Review Queue
CREATE POLICY "Users can view own ml coding reviews"
  ON ml_coding_review_queue FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own ml coding reviews"
  ON ml_coding_review_queue FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own ml coding reviews"
  ON ml_coding_review_queue FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own ml coding reviews"
  ON ml_coding_review_queue FOR DELETE
  USING (auth.uid() = user_id);

-- ============ Anon Policies (API service key) ============

-- Problems
CREATE POLICY "Anon can view all ml coding problems"
  ON ml_coding_problems FOR SELECT TO anon
  USING (true);

-- Daily Exercises
CREATE POLICY "Anon can view all ml coding exercises"
  ON ml_coding_daily_exercises FOR SELECT TO anon
  USING (true);

CREATE POLICY "Anon can insert all ml coding exercises"
  ON ml_coding_daily_exercises FOR INSERT TO anon
  WITH CHECK (true);

CREATE POLICY "Anon can update all ml coding exercises"
  ON ml_coding_daily_exercises FOR UPDATE TO anon
  USING (true);

CREATE POLICY "Anon can delete all ml coding exercises"
  ON ml_coding_daily_exercises FOR DELETE TO anon
  USING (true);

-- Review Queue
CREATE POLICY "Anon can view all ml coding reviews"
  ON ml_coding_review_queue FOR SELECT TO anon
  USING (true);

CREATE POLICY "Anon can insert all ml coding reviews"
  ON ml_coding_review_queue FOR INSERT TO anon
  WITH CHECK (true);

CREATE POLICY "Anon can update all ml coding reviews"
  ON ml_coding_review_queue FOR UPDATE TO anon
  USING (true);

CREATE POLICY "Anon can delete all ml coding reviews"
  ON ml_coding_review_queue FOR DELETE TO anon
  USING (true);

-- ============ RPC Functions ============

CREATE OR REPLACE FUNCTION get_due_ml_coding_reviews(p_user_id UUID, p_limit INTEGER DEFAULT 10)
RETURNS SETOF ml_coding_review_queue
LANGUAGE sql STABLE
AS $$
  SELECT *
  FROM ml_coding_review_queue
  WHERE user_id = p_user_id
    AND next_review <= NOW()
  ORDER BY priority DESC, next_review ASC
  LIMIT p_limit;
$$;

CREATE OR REPLACE FUNCTION complete_ml_coding_review(p_review_id UUID, p_success BOOLEAN)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  IF p_success THEN
    UPDATE ml_coding_review_queue
    SET interval_days = LEAST(interval_days * 2, 30),
        next_review = NOW() + (LEAST(interval_days * 2, 30) || ' days')::INTERVAL,
        review_count = review_count + 1,
        last_reviewed = NOW()
    WHERE id = p_review_id;
  ELSE
    UPDATE ml_coding_review_queue
    SET interval_days = 1,
        next_review = NOW() + INTERVAL '1 day',
        review_count = review_count + 1,
        last_reviewed = NOW()
    WHERE id = p_review_id;
  END IF;
END;
$$;

-- ============ Seed Data: 10 ML Coding Problems ============

INSERT INTO ml_coding_problems (slug, title, description, difficulty, category, key_concepts, math_concepts, estimated_minutes, sort_order) VALUES
(
  'k-means',
  'Implement K-Means Clustering',
  'Implement the k-means clustering algorithm from scratch. Given a set of data points and k, initialize centroids, assign points to nearest centroid, update centroids, and repeat until convergence. Handle edge cases like empty clusters.',
  'medium',
  'clustering',
  ARRAY['centroid initialization', 'distance computation', 'convergence check', 'cluster assignment'],
  ARRAY['Euclidean distance', 'mean computation', 'convergence criteria'],
  30,
  1
),
(
  'logistic-regression',
  'Implement Logistic Regression with Gradient Descent',
  'Implement binary logistic regression from scratch using gradient descent. Include the sigmoid function, binary cross-entropy loss, gradient computation, and weight update step. Support configurable learning rate and number of iterations.',
  'medium',
  'classification',
  ARRAY['sigmoid function', 'cross-entropy loss', 'gradient descent', 'weight updates'],
  ARRAY['sigmoid derivative', 'log-likelihood', 'gradient of BCE', 'learning rate'],
  35,
  2
),
(
  'pca',
  'Implement PCA from Scratch',
  'Implement Principal Component Analysis using either SVD or covariance eigendecomposition. Center the data, compute covariance matrix or SVD, extract top-k principal components, and project data onto the new basis.',
  'hard',
  'dimensionality_reduction',
  ARRAY['data centering', 'covariance matrix', 'eigendecomposition', 'variance explained'],
  ARRAY['SVD', 'eigenvalues', 'eigenvectors', 'covariance', 'projection'],
  40,
  3
),
(
  'decision-tree-splitter',
  'Implement a Decision Tree Splitter',
  'Implement the core splitting logic for a decision tree classifier. For each feature, find the best split point that maximizes information gain (or minimizes Gini impurity). Return the best feature index, threshold, and resulting child node indices.',
  'hard',
  'trees',
  ARRAY['information gain', 'Gini impurity', 'split threshold', 'recursive partitioning'],
  ARRAY['entropy', 'Gini index', 'weighted impurity', 'information gain formula'],
  40,
  4
),
(
  'classification-metrics',
  'Implement Binary Classification Metrics',
  'Implement precision, recall, F1 score, and ROC-AUC from scratch given arrays of true labels and predicted probabilities. Include threshold-based metrics and the full ROC curve computation via sweeping thresholds.',
  'easy',
  'evaluation',
  ARRAY['confusion matrix', 'precision/recall', 'F1 score', 'ROC curve', 'AUC'],
  ARRAY['true positive rate', 'false positive rate', 'trapezoidal rule for AUC'],
  25,
  5
),
(
  'cosine-similarity',
  'Implement Cosine Similarity Retrieval',
  'Implement cosine similarity between embedding vectors and build a simple retrieval system. Given a query embedding and a corpus of document embeddings, return the top-k most similar documents ranked by cosine similarity.',
  'easy',
  'retrieval',
  ARRAY['dot product', 'vector normalization', 'top-k retrieval', 'similarity ranking'],
  ARRAY['cosine similarity formula', 'L2 norm', 'dot product'],
  20,
  6
),
(
  'matrix-factorization',
  'Implement Matrix Factorization Recommender',
  'Implement a simple matrix factorization recommender using alternating least squares or SGD. Given a sparse user-item rating matrix, learn latent factor matrices U and V such that R ≈ U @ V.T. Support prediction for unseen user-item pairs.',
  'hard',
  'recommenders',
  ARRAY['latent factors', 'SGD optimization', 'rating prediction', 'regularization'],
  ARRAY['Frobenius norm', 'gradient of squared error', 'L2 regularization', 'matrix decomposition'],
  45,
  7
),
(
  'beam-search',
  'Implement Beam Search Decoding',
  'Implement beam search for sequence decoding. Given a function that returns next-token log-probabilities, maintain k beams (partial sequences with cumulative scores), expand each beam, prune to top-k, and return the best complete sequence.',
  'medium',
  'decoding',
  ARRAY['beam width', 'log-probability accumulation', 'pruning', 'end-of-sequence handling'],
  ARRAY['log-probability', 'length normalization', 'top-k selection'],
  30,
  8
),
(
  'ranking-metrics',
  'Implement NDCG and MRR for Ranking',
  'Implement Normalized Discounted Cumulative Gain (NDCG) and Mean Reciprocal Rank (MRR) from scratch. Given ranked lists of items with relevance scores, compute DCG, ideal DCG, NDCG@k, and MRR across multiple queries.',
  'medium',
  'evaluation',
  ARRAY['DCG computation', 'ideal ordering', 'NDCG normalization', 'reciprocal rank'],
  ARRAY['log2 discount', 'DCG formula', 'IDCG', 'reciprocal rank'],
  25,
  9
),
(
  'ab-test-analysis',
  'Implement A/B Test Analysis with Confidence Intervals',
  'Write a function that takes control and treatment group outcomes and computes: sample means, pooled standard error, z-statistic, p-value, and 95% confidence interval for the difference in means. Determine statistical significance.',
  'easy',
  'experimentation',
  ARRAY['hypothesis testing', 'confidence intervals', 'p-value', 'effect size'],
  ARRAY['z-test', 'standard error', 'normal distribution', 'pooled variance', 'confidence interval formula'],
  20,
  10
);
