steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/leetloop-api:latest'
      - '-f'
      - 'api/Dockerfile'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/leetloop-api:latest'
